name: SonarCloud Analysis

on:
  push:
    branches: [ "main", "testbranch", "testmaster" ] # Triggers on push to these branches
  pull_request:
    branches: [ "main", "testbranch", "testmaster" ] # Triggers on PRs targeting these branches
    types: [opened, synchronize, reopened]

jobs:
  SonarCloud-Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Essential for correct analysis

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Tests and Generate Coverage Report
        run: |
          pip install pytest pytest-cov
          pytest --cov=./ --cov-report=xml:coverage.xml -v

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=tests/**,**/__init__.py
            # SonarCloud automatically detects the branch for PRs
            # For push events, we need to tell it the branch name.
            -Dsonar.branch.name=${{ github.ref_name }}